name: AMI format test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: zip all files
        run: zip -r webapp.zip .

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip -o packer_1.7.2_linux_amd64.zip -d /tmp
          chmod +x /tmp/packer
          sudo mv /tmp/packer /usr/local/bin/
          packer version
      
      - name: Run Packer pulgin installation
        run: packer init ./packer/webapp.pkr.hcl

      - name: Run Packer fmt
        run: packer fmt -check ./packer/webapp.pkr.hcl

      - name: Run Packer validate
        run: packer validate -var-file="./packer/variableFile.pkrvars.hcl" ./packer/webapp.pkr.hcl