name: AMI build

on:
  push:
    branches: [temp]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: zip all files
        run: zip -r webapp.zip .

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip -o packer_1.7.2_linux_amd64.zip -d /tmp
          chmod +x /tmp/packer
          sudo mv /tmp/packer /usr/local/bin/
          packer version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Packer pulgin installation
        run: packer init ./packer/webapp.pkr.hcl

      - name: Run Packer file
        run: packer build -var-file="./packer/variableFile.pkrvars.hcl" ./packer/webapp.pkr.hcl

      - name: Get latest AMI ID
        run: |
          latest_ami=$(aws ec2 describe-images --filters "Name=name,Values=csye6225*" --query "Images | [0].ImageId" --output text)
          echo "Latest AMI ID: $latest_ami"

      - name: Create Launch Template
        run: |
          aws ec2 create-launch-template-version --launch-template-name launchtemplate-ecd9475 --source-version 1 --launch-template-data '{"ImageId":"$latest_ami"}'
          latest_version=$(aws ec2 describe-launch-template-versions --launch-template-name launchtemplate-ecd9475 --query "LaunchTemplateVersions[-1].VersionNumber" --output text)
          aws ec2 modify-launch-template-default-version --launch-template-name launchtemplate-ecd9475 --default-version "$latest_version"

      - name: Refresh autoscaling group
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name autoscaling-group
