name: AMI format test

on:
  pull_request:
    branches: [demo]

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo pd=${{ secrets.PD }}>> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
          packer version
      
      - name: Run Packer pulgin installation
        run: packer init .

      - name: Run Packer fmt
        run: packer fmt -check .

      - name: Run Packer validate
        run: packer validate -var-file="variableFile.pkrvars.hcl" -var 'USER=${{ secrets.USER }}' -var 'DATABASE=${{ secrets.DATABASE }}' -var 'PD=${{ secrets.PD }}' webapp.pkr.hcl