name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          dialect: ${{ secrets.DIALECT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          database: ${{ secrets.DATABASE }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
      - run: npm ci
      - run: npm run test
        env:
          dialect: ${{ secrets.DIALECT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          database: ${{ secrets.DATABASE }}
