name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull MySQL Docker image
        run: docker pull mysql:latest

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
      
      - name: Wait for MySQL to be ready
        run: |
          while ! docker exec mysql mysqladmin ping -u${{ secrets.USER }} -p${{ secrets.PD }} --host 127.0.0.1 --port 3306 --silent; do
            echo "Waiting for MySQL to start..."
            sleep 5
          done

      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo pd=${{ secrets.PD }} >> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - run: npm ci
      - run: npm run test
