name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 15672N@vin
          MYSQL_DATABASE: cloud
        ports:
          - 3306

    steps:
      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0

      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo pd=${{ secrets.PD }} >> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - run: npm ci
      - run: npm run test