name: CI

on:
  pull_request:    
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm init -y
      - run: npm install sequelize
      - run: npm install chai
      - run: npm install mocha
      - run: npm install cors
      - run: npm install dotenv
      - run: npm install express
      - run: npm install supertest
      - run: npm install mysql
      - run: npm install mysql2
      - run: |
          echo "Dialect: ${{ secrets.env.dialect }}"
          echo "Host: ${{ secrets.env.host }}"
          echo "Port: ${{ secrets.env.port }}"
          echo "User: ${{ secrets.env.user }}"
          echo "Password: ${{ secrets.env.password }}"
          echo "Database: ${{ secrets.database }}"
      - run: npm run test 
        env:
          dialect: ${{ secrets.dialect }}
          host: ${{ secrets.host }}
          port: ${{ secrets.port}}
          user: ${{ secrets.user }}
          password: ${{ secrets.password }}
          database: ${{ secrets.database }}