name: CI

on:
  pull_request:
    branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     services:
#       mysql:
#         image: mysql:latest
#         env:
#           MYSQL_ROOT_PASSWORD: ${{ secrets.PD }}
#           MYSQL_DATABASE: ${{ secrets.DATABASE }}
#           MYSQL_USER: ${{ secrets.USER }}
#         ports:
#           - 3306:8080

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18.18.0

#       - name: create and configure
#         run: |
#           touch .env
#           echo port=${{ secrets.PORT }} >> .env
#           echo host=${{ secrets.HOST }} >> .env
#           echo dialect=${{ secrets.DIALECT }} >> .env
#           echo user=${{ secrets.USER }} >> .env
#           echo pd=${{ secrets.PD }} >> .env
#           echo database=${{ secrets.DATABASE }} >> .env

#       - run: npm ci
#       - run: npm run test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize MySQL
        run: sudo systemctl start mysql.service

      # - name: Boost user
      #   run: |
      #     mysql -e "ALTER USER '${{ secrets.USER }}'@'localhost' \
      #     IDENTIFIED WITH mysql_native_password BY 'root';" \
      #     -u${{ secrets.USER }} -p${{ secrets.PD }}

      - name: check for privilages
        run: mysql -e "GRANT ALTER, UPDATE ON mysql.* TO 'runner'@'localhost';"

      - name: Initialize first database
        run: mysql -e "ALTER USER '${{secrets.USER}}'@'localhost' IDENTIFIED BY '${{secrets.PD}}'";

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: run tests
        run: |
          MYSQL_USERNAME=${{secrets.USER}} \
          MYSQL_PASSWORD=${{secrets.PD}} \
          MYSQL_ACTIVE_DATABASE=${{secrets.DATABASE}} \
        
      - run: npm ci
      - run: npm run test