name: CI

on:
  pull_request:    
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm init -y
      - run: npm install sequelize
      - run: npm install chai
      - run: npm install mysql
      - run: npm install mocha
      - run: npm install cors
      - run: npm install dotenv
      - run: npm install express
      - run: npm install supertest
      - run: npm install
      - run: npm run test