name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          dialect: ${{ secrets.DIALECT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          database: ${{ secrets.DATABASE }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.0
      
      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo pd=15672N@vin >> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - run: npm ci
      - run: pwd 
      - run: ls && cat .env
      - run: npm run test
        env:
          dialect: ${{ secrets.DIALECT }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          database: ${{ secrets.DATABASE }}
