name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm init -y
      - run: npm install sequelize
      - run: npm install chai
      - run: npm install mocha
      - run: npm install cors
      - run: npm install dotenv
      - run: npm install express
      - run: npm install supertest
      - run: npm install mysql
      - run: npm install mysql2
      - name: Set Environment Variables
        run: |
          echo "Dialect: ${{ secrets.DIALECT }}"
          echo "Host: ${{ secrets.HOST }}"
          echo "Port: ${{ secrets.PORT }}"
          echo "User: ${{ secrets.USER }}"
          echo "Password: ${{ secrets.PASSWORD }}"
          echo "Database: ${{ secrets.DATABASE }}"
          export DIALECT="${{ secrets.DIALECT }}"
          export HOST="${{ secrets.HOST }}"
          export PORT="${{ secrets.PORT }}"
          export USER="${{ secrets.USER }}"
          export PASSWORD="${{ secrets.PASSWORD }}"
          export DATABASE="${{ secrets.DATABASE }}"
      - run: npm run test
        env:
          DIALECT: ${{ secrets.DIALECT }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          DATABASE: ${{ secrets.DATABASE }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
